---
  - name: VM
    hosts: all
    become: yes
    become_user: root

    tasks:
      - name: enable EPEL
        yum:
          name:
            - epel-release

      - name: update OS
        yum:
          name: '*'
          state: latest

      - name: reboot from update
        reboot:
          reboot_timeout: 90

      - name: install needed packages
        yum:
          name:
            - java-11-openjdk-headless
            - nginx
            - mariadb-server
            - mariadb-java-client
            - dnf-automatic

      - name: enable yum-cron updates
        lineinfile:
          path: /etc/dnf/automatic.conf
          regexp: 'apply_updates = no'
          line: apply_updates = yes

      - name: enable services
        service:
          name: "{{ item }}"
          enabled: yes
          state: started
        with_items:
          - nginx
          - mariadb
          - dnf-automatic.timer
